### ISSUE TITLE
Issue Prioritization

### ISSUE THREAD

**Issue by jcf2** [TACC/a2cps-datastore-imaging#17]
(Until we hopefully get the ability to set labels on issues, this tracks what is highest priority.)

- [X] #5 
- [X] #12 
- [x] #11 and #15
- [x] #16, so we can add that key of site codes/site names
- [x] #10 
- [ ] #13 and #14 (Cuff Pressure tab)
- [x] #26
- [ ] #11 and #15 (Heat Map tab)

**Comment by jcf2** [comment]
I switched from a bulleted list to a Task List. Hope that won't somehow confuse things.

**Comment by mepearson** [comment]
@jcf2 - #4 and #5 done.

**Comment by jcf2** [comment]
OK, I'm extending the list, since it seems this is the best we can do for now. My reasoning was to address correctness issues (Cuff Pressure), followed by efficiency, followed by dealing with the Heat Map tab in some way (revise or eliminate).
